language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install https://github.com/InfoAgeTech/django-tools/tarball/master
  - pip install https://github.com/InfoAgeTech/python-tools/tarball/master
  - pip install django_nose
  - python setup.py -q install
# command to run tests
script:
  - python manage.py test
branches:
  only:
    - master