language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6.9
matrix:
  include:
    - python: "3.3"
      env: DJANGO_VERSION=1.7.2
    - python: "3.4"
      env: DJANGO_VERSION=1.7.2
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install https://github.com/InfoAgeTech/django-tools/tarball/master
  - pip install https://github.com/InfoAgeTech/python-tools/tarball/master
  - pip install django_nose
  - python setup.py -q install
# command to run tests
script:
  - python manage.py test
branches:
  only:
    - master